
key_file: 'mesh' #default

input_file: '27x27x27.msh'
output_file: '27x27x27'

#malha fina
Level0:
  #Comprimento do reservatório
  L: [27, 27, 27]
  # numero de blocos da malha fina
  nb: [27, 27, 27]

delta: 1e-6
gravity: True

Levels:
  Nv1:
    L: [3.0, 3.0, 3.0]

  Nv2:
    L: [9.0, 9.0, 9.0]
